services:
  database:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: eeeeee
      MONGO_INITDB_DATABASE: secure_pass
      MONGO_INITDB_ROOT_USERNAME: admin
    container_name: mongo_db